spring.datasource.url: jdbc:h2:mem:BookMyCab
#spring.datasource.url: jdbc:h2:file:./data/h2
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: admin
spring.datasource.password: admin
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto: create-drop
spring.jpa.show-sql: true

#logging.level.org.springframework:  DEBUG
#logging.level.org.hibernate:  DEBUG

bookMyCab.app.jwtSecret: BookMyCabSecretKey
bookMyCab.app.jwtExpirationMs: 1000000
bookmycab.app.allowed-resources: /home/**,/h2-console/**,/v3/api-docs/**,/swagger-ui.html,/swagger-ui/**